### PR TITLE
Tweaked markdown output and added support for csv format.

### PR DESCRIPTION
**Pull request by jtan189**

### CODE REVIEW

**Comment by suite22** [comment]
@twaddington any plans to merge this back in? Now that Rdio is shutting down I'm sadly exporting everything.

**Comment by twaddington** [comment]
Sorry, I'll take a look at this tonight.

**Comment by suite22** [comment]
Yeah sorry @twaddington I wasn't trying to be an ass about it. Just wanted to double check before creating another fork. :+1:

**Comment by twaddington** [comment]
@suite22 didn't take it that way at all. I've just let this go too long without reviewing it.

Pulling this down right now so I can rebase it and test it out.

**Comment by twaddington** [comment]
Okay, I merged this in and made a few minor tweaks. Gonna push out `1.3.0` to PyPi shortly.

@suite22 let me know if you have any issues.

**Pull request closed without merging**
