### PR TITLE
Adding ability to export collection by artist, album, or track.

### PR DESCRIPTION
**Pull request by jtan189**
Addresses issue #6.

### CODE REVIEW

**Comment by twaddington** [comment]
Thanks @jtan189 this looks good to me. I'm gonna go ahead and merge this in. Will test and cut a new release sometime this week.

I'm at Google I/O currently and will be pretty busy the next couple days.

**Comment by twaddington** [comment]
Hey @jtan189 I took a look at this today and it doesn't really do what I would expect, so I ended up reverting this merge.

Basically by default the script outputs a list of your collection in markdown format with artist and album titles as headers and a list of tracks in that album following. I think this should be the default behavior.

For a flat listing that's less oriented around album I would suggest the following format (sorted by artist, album then track):

```
{track}, {album}, by {artist}
{track}, {album}, by {artist}
{track}, {album}, by {artist}
...
```

Instead of a flat option we could simply add a `--format csv` option instead if that's what folks want.

**Comment by jtan189** [comment]
Hey @twaddington. Just making sure I'm on the same page. Currently, the script output something like:

```
## Artist 1
  - Album 1
  - Album 2

## Artist 2
  - Album 3
...
```

In this current version, no track information is printed. You want this to remain the default behavior, correct?

There seems to be two topics here: 1) level of detail/abstraction with which to report the rdio collection (artist, artist/album, or artist/album/track), and 2) output format (markdown, csv, etc.). Do you think there should be options to choose from both of these? I think that would be useful. Also, I'd prefer the `--format csv` option over the flat listing option, with something like:

```
{track},{album},{artist}
{track},{album},{artist}
...
```

**Comment by twaddington** [comment]
Yeah, I'm interested to hear what you think about this. You're correct, the current behavior just outputs artists and albums. The intent was to build a human-readable document so that if the worst happened and I had to go into a record store and rebuild my collection I'd ~~know what albums to buy~~ have a shopping list.

This could be updated to include track details. Possibly something like:

``` markdown
## Artist 1
  ### Album 1
    - Track 1
    - Track 2
    - Track 3
  ### Album 2
    - Track 1
    - Track 2
    - Track 3

## Artist 2
  ### Album 1
    - Track 1
...
```

Additionally, we could include a flat csv format that was easier to parse from other import scripts. This has the added benefit of also including track details.

I'm down with doing one or the other or both. Also up for other suggestions but I do want to maintain the default behavior of outputting a markdown document because it's human friendly.

**Comment by twaddington** [comment]
Thinking about the csv format it should probably be ordered as:

```
{artist},{album},{track}
{artist},{album},{track}
{artist},{album},{track}
...
```

**Comment by jtan189** [comment]
The default of md is reasonable. I've implemented both. See what you think.

**Pull request merged**
